### ISSUE TITLE
Extracting UMDIMAGE.DAT from the full PSP version of Danganronpa 1 and the CPK file of the Vita version doesn't work.

### ISSUE THREAD

**Issue by Shorty332** [Liquid-S/Danganronpa-Another-Tool#12]
![Screenshot (421)](https://user-images.githubusercontent.com/61999674/185269419-d4a1ffc0-2832-493b-aded-9a2d5618a876.png)
I am getting this message every time I attempt to extract "UMDIMAGE.DAT" from the full version of Danganronpa 1. Attempting to continue after the error merely does nothing but tells me to wait and attempting to extract the CPK from Vita version says it extracted the files from "CPK" file but shows no file.

**Comment by lonkalsim** [comment]
same with repack .pak

**Comment by VoxelTek** [comment]
I also get this error, and I've provided it with a decrypted eboot.bin, and multiple different umdimage.dat files.

Here's the error I seem to be getting:
```
************** Exception Text **************
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.ReadByte()
   at Danganronpa_Another_Tool.DATpsp.ExtractDAT(String IndirizzoUMDIMAGE, String DestinationDir, Int64 pos, String FILEBOOT, String GameVersion)
   at Danganronpa_Another_Tool.DRAT.Button5_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

I can attach the full error log if necessary, but it's mostly just listing loaded assemblies.

Any chance you'd be able to help solve this issue, @Liquid-S ? Sorry to be a bother about this.

**Comment by VoxelTek** [comment]
I believe I've solved it. I think it only works with the PSP The Best version of the game. Either that, or the Project Zetsubousu (or whatever) translated version. Either way, using that version works flawlessly. @Shorty332 I think this might help you.
